# Generated by Django 2.2.1 on 2019-05-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190505_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
