# Generated by Django 2.2.1 on 2019-05-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='professional_license',
            field=models.ImageField(upload_to='licenses'),
        ),
    ]
